# Generated by Django 2.0.4 on 2018-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20180529_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_standalone',
        ),
        migrations.AddField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
    ]
