# Generated by Django 2.0.4 on 2018-06-04 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20180604_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='device.Version'),
        ),
    ]
