# Generated by Django 2.0.4 on 2018-06-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_auto_20180604_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicegroup',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='groups', to='device.Device'),
        ),
    ]
